meta:
  title: 最初の特徴量だけ
shared:
  train_path: projects/sony/data/train_v4.csv
  test_path: projects/sony/data/test_v4.csv
  features_dir: projects/sony/data/features
  # register_from: projects.airbnb.custom.feature_generators
  target_col: pm25_mid
  seed: 42
  folds_gen_str: group
  group_key_col: City
  model_str: lgbm_rmse
  evaluator_str: rmse
  unused_cols: 
  - id 
  - City
  - yyyymmdd
  #target_enc_cols:
  #- Country
  #log_target_on_target_enc: False
jobs:
- params: 
    seed: 42

#stacking:
#  shared:
#    "use_original_cols": False
#  stacking_settings:
#  - 
#    - avg_rmsle
#    - linear_rmsle
#    - ridge_rmsle
#    - lgbm_rmsle
#  - 
#    - avg_rmsle

