meta:
  title: 004にabstract_bertとkeyword_first_yearの変更
  description: 同じ
shared:
  train_path: data/train_data.csv
  test_path: data/test_data.csv
  features_dir: data/features
  register_from: projects/prob_ac/custom
  extra_class_names: 
    - KeywordsLengthFeature
    - KeywordsAverageYear
    - KeywordsAverageCount
    - KeywordsFirstYear
  target_col: y
  fold_num: 5
  seed: 42
  folds_gen_str: stratified
  model_str: lgbm_bin # catb_bin
  evaluator_str: accuracy
  #min_child_samples: 10
  #class_weight: balanced
  unused_cols: 
  - id 
  - title
  - abstract
  - keywords
  - year
  features_settings:
    - model_str: keywords_length_feature
    - model_str: keywords_average_count
    - model_str: text_length
      params:
        input_col: title
    - model_str: text_length
      params:
        input_col: abstract
    - model_str: sentence_vector_dec
      params: 
        input_col: abstract
        vectorizer_str: bert 
        decomposer_str: svd
        n_components: 20
        seed: 42
        
      

jobs:
- name: seed42
  params: 
    seed: 42

