meta:
  title: 009+cat_lda(district, layout, 5)

shared:
  train_path: projects/house_price/data/train_v2.csv
  test_path: projects/house_price/data/test_v2.csv
  features_dir: projects/house_price/data/features
  # register_from: projects.house_price.custom.feature_generators
  target_col: price_log
  seed: 42
  folds_gen_str: group
  group_key_col: ordered
  model_str: lgbm_mae
  evaluator_str: mae
  unused_cols: 
  - id 
  - ordered
  - built_year
  target_enc_cols:
  - nearest_sta
  - district
  log_target_on_target_enc: False
  features_settings:
  - model_str: cat_lda
    params:
      main_col: district
      sub_col: layout
      num_topics: 5
jobs:
- params: 
    seed: 42

#stacking:
#  shared:
#    "use_original_cols": False
#  stacking_settings:
#  - 
#    - avg_rmsle
#    - linear_rmsle
#    - ridge_rmsle
#    - lgbm_rmsle
#  - 
#    - avg_rmsle

