meta:
  title: lgbmのdiff有無でseed_average

shared:
  train_path: projects/house_price/data/train_v5.csv
  test_path: projects/house_price/data/test_v5.csv
  features_dir: projects/house_price/data/features/v5
  # register_from: projects.house_price.custom.feature_generators
  target_col: price_log
  base_col: area_log
  seed: 42
  detph: 8
  folds_gen_str: group
  group_key_col: ordered
  #model_str: lgbm_diff_mae
  evaluator_str: mae
  unused_cols: 
  - id 
  - ordered
  - built_year # 西暦を使っているから
  - area # area_logを使っているから 
  - nearest_min # nearest_min_logを使っているから
  - age # ageを使っているから
  target_enc_cols:
  - nearest_sta
  - district
  log_target_on_target_enc: False
  features_settings:
  - model_str: group
    params:
      group_keys:
      - city
      - district
      - nearest_sta
      agg_func_list:
      - mean
      input_cols:
      - built_year_seireki
      - area
      - nearest_min
      - age
      - area_log
      - nearest_min_log
      - age_log
  - model_str: cat_lda
    params:
      main_col: city
      sub_col: layout
      num_topics: 5
      
jobs:
- name: lgbm_mae_1
  params: 
    model_str: lgbm_mae
    seed: 1

- name: lgbm_mae_2
  params: 
    model_str: lgbm_mae
    seed: 2

- name: lgbm_mae_3
  params: 
    model_str: lgbm_mae
    seed: 3

- name: lgbm_mae_4
  params: 
    model_str: lgbm_mae
    seed: 4

- name: lgbm_mae_5
  params: 
    model_str: lgbm_mae
    seed: 5

- name: lgbm_diff_mae_1
  params: 
    model_str: lgbm_diff_mae
    seed: 6

- name: lgbm_diff_mae_2
  params: 
    model_str: lgbm_diff_mae
    seed: 7

- name: lgbm_diff_mae_3
  params: 
    model_str: lgbm_diff_mae
    seed: 8

- name: lgbm_diff_mae_4
  params: 
    model_str: lgbm_diff_mae
    seed: 9

- name: lgbm_diff_mae_5
  params: 
    model_str: lgbm_diff_mae
    seed: 10

    


stacking:
  shared:
    "use_original_cols": False
  stacking_settings:
  - 
    - avg_mae
