target_col: y
features_dir: data/features
seed: 42
trainer_str: basic
folds_gen_str: group
fold_num: 5
depth: 5
train_path: data/train_data.csv
test_path: data/test_data.csv
group_key_col: host_id
model_str: lgbm_rmsle
folds_gen_str: group
evaluator_str: rmsle
unused_cols: 
 - id 
 - host_id
 - name
 - last_review
 - last_review_day
n_estimators: 2000
features_settings:
  - model_str: datetime
    params:
      input_col: last_review
  - model_str: pipeline
    params:
      feature_generators:
      - model_str: preprocess_name
      - model_str: wc_vec
        params:
          decomposer_str: svd
          input_col: name_preprocessed
          n_components: 32
          random_state: 42
          vectorizer_str: tfidf
  - model_str: pipeline
    params:
      feature_generators:
      - model_str: preprocess_name
      - model_str: wc_vec
        params:
          decomposer_str: nmf
          input_col: name_preprocessed
          n_components: 10
          random_state: 42
          vectorizer_str: tfidf
  - model_str: pipeline
    params:
      feature_generators:
      - model_str: preprocess_name
      - model_str: wc_vec
        params:
          decomposer_str: svd
          input_col: name_preprocessed
          n_components: 32
          random_state: 42
          vectorizer_str: bow
  - model_str: pipeline
    params:
      feature_generators:
      - model_str: preprocess_name
      - model_str: wc_vec
        params:
          decomposer_str: nmf
          input_col: name_preprocessed
          n_components: 10
          random_state: 42
          vectorizer_str: bow
  - model_str: pipeline
    params:
      feature_generators:
      - model_str: preprocess_name
      - model_str: bert
        params:
          input_col: name_preprocessed
          max_len: 128
          model_name: bert-base-multilingual-uncased
      - model_str: dec
        params:
          col_mark: bert
          decomposer_str: pca
          n_components: 20
          random_state: 42
      use_prev_only: true
  - model_str: pipeline
    params:
      feature_generators:
      - model_str: preprocess_name
      - model_str: bert
        params:
          input_col: name_preprocessed
          max_len: 128
          model_name: bert-base-multilingual-uncased
      - model_str: dec
        params:
          col_mark: bert
          decomposer_str: umap
          n_components: 10
          random_state: 42
      use_prev_only: true
  - model_str: pipeline
    params:
      feature_generators:
      - model_str: preprocess_name
      - model_str: rulebase_name
  - model_str: extra_join
    params:
      csv_path: data/nearest_station.csv
      join_on: id
  - model_str: extra_join
    params:
      csv_path: data/dist_under_counts.csv
      join_on: id
  - model_str: extra_join
    params:
      csv_path: data/nearest_terminal.csv
      join_on: id
  - model_str: cluster
    params:
      input_cols:
      - latitude
      - longitude
      model_str: gmm
      n_clusters: 10
      random_state: 42
  - model_str: cluster
    params:
      input_cols:
      - latitude
      - longitude
      model_str: kmeans
      n_clusters: 10
      random_state: 42
  - model_str: pipeline
    params:
      feature_generators:
      - model_str: extra_join
        params:
          csv_path: data/nearest_station.csv
          join_on: id
      - model_str: cluster
        params:
          input_cols:
          - sta_latitude
          - sta_longitude
          model_str: kmeans
          n_clusters: 10
          random_state: 42
  - model_str: pipeline
    params:
      feature_generators:
      - model_str: extra_join
        params:
          csv_path: data/nearest_station.csv
          join_on: id
      - model_str: cluster
        params:
          input_cols:
          - sta_latitude
          - sta_longitude
          model_str: gmm
          n_clusters: 10
          random_state: 42
  - model_str: pipeline
    params:
      feature_generators:
      - model_str: extra_join
        params:
          csv_path: data/nearest_station.csv
          join_on: id
      - model_str: group
        params:
          group_key: station_name
          input_cols:
          - minimum_nights
          - number_of_reviews
          - availability_365
      - model_str: dec
        params:
          col_mark: station_group
          decomposer_str: umap
          n_components: 10
          random_state: 42
      use_prev_only:
      - false
      - true
  - model_str: reviewed_month
register_from: custom.feature_generators